# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.6
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    
    - name: Zip the application files
      run: zip -r myapp.zip .
    - name: 'Deploy to Azure Web App'
      uses: azure/webapps-deploy@v1
      with:
        app-name: 'drowntestapi'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_9f42a6cc8fcc46d782a7647cf40bab89 }}
        package: './myapp.zip'
